name: CI
on: [push, pull_request]

# env:
#   NPM_TOKEN: ${{secrets.NPM_TOKEN_READ_ONLY}}
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Shellcheck linter config
        run: |

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color

