name: Notify Committer Re-useable workflow
## How to

# 1. add you github username and slack userID or a channelID to the json (user-mapping: ... ) below:
#    - userID: https://www.workast.com/help/article/how-to-find-a-slack-user-id/) or
#    - channelID: https://help.socialintents.com/article/148-how-to-find-your-slack-team-id-and-slack-channel-id)
# 2. add "github-integration" Slack app to you apps by clicking https://app.slack.com/client/T048C4TSA/D04CSKKC2BT
# 3. now you'll get notified about failing builds etc.
on:
  workflow_call:
    inputs:
      failure:
        required: true
        type: boolean
    secrets:
      SLACK_BOT_TOKEN:
        required: true
env:
  DEV_CHANNEL_ID: "C013PVCCD3R"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve slack committer
        id: slack-committer
        uses: livelyhood/slack-committer@main
        with:
          # see above or TLDR; https://www.workast.com/help/article/how-to-find-a-slack-user-id/
          user-mapping: >
            {
              "penchef": "UUSAQBVDZ",
              "fallback": ${{ env.DEV_CHANNEL_ID }}
            }
      - name: Notify user
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: ${{ inputs.failure }}
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        with:
          channel_id: ${{ steps.slack-committer.outputs.username }}
          status: FAILED
          color: danger
      - name: Notify \#dev when on main
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: ${{ inputs.failure }}  && github.ref == 'refs/heads/main'
        uses: voxmedia/github-action-slack-notify-build@v1.5.0
        with:
          channel_id: ${{ env.DEV_CHANNEL_ID }}
          status: FAILED
          color: danger
