name: CI
on: [ pull_request ]


jobs:
  label:
    uses: ./.github/workflows/size-label-caller.yml@sl/feature/prlabler
    with:
      sizes: >
        {
          "0": "XS",
          "10": "S",
          "30": "M",
          "50": "L",
          "150": "XL",
          "300": "TOO-LARGE",
          "500": "WAAY TOO LARGE"
        }

